
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-06
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY3MDI5MzIw","is_bot":false,"login":"andrewzshen","name":"Andrew Shen"},"headRefName":"andrew-make-moderate-reviews","number":30,"title":"Andrew - Added Moderate Reviews Page","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/30"},{"author":{"id":"U_kgDOB2QqkQ","is_bot":false,"login":"jml557","name":"Julia L"},"headRefName":"jml-replace-example-brand","number":27,"title":"jml - change NavBar and browser titles to \"UCSB Dining\"","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/27"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-utc-to-local-time","number":21,"title":"NF - Dates No Longer Default to UTC","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/21"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-add-meal-options-to-main-page","number":18,"title":"NF - Adds \"Meals Offered Today\" Column to Main Page","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/18"}]
