
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-06
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-06
pull_requests: [{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-add-meal-options-to-main-page","number":18,"title":"nf - on the main page, add a column that shows the meals offered at t…","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/18"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-bug-fix-for-error-msgs-on-days-hall-closed","number":17,"title":"nf - fix a bug where on days the dining hall is closed a 500 error co…","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/17"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"helenlongjiao-refactor-relative-imports","number":16,"title":"REFACTOR: replace relative paths in imports with absolute paths","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/16"}]
