
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-dining-f25-06
owner: ucsb-cs156-f25
repo_name: proj-dining-f25-06
pull_requests: [{"author":{"id":"U_kgDOCVy2iQ","is_bot":false,"login":"AbhiramA02","name":""},"headRefName":"aa-add-date-selector-home","number":22,"title":"AA - Feature/Tests Implementation Date Selector on Home Page","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/22"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-utc-to-local-time","number":21,"title":"NF - Dates No Longer Default to UTC","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/21"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-add-loading-message-for-slow-api-calls","number":20,"title":"NF - Implementation Adjustment to Previous Bug Fix PR","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/20"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"helenlongjiao-fix-footer-link","number":19,"title":"longjiao - FEATURE: Fix link in Footer","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/19"},{"author":{"id":"U_kgDOCm9VLg","is_bot":false,"login":"fortenatalie","name":"Natalie Forte"},"headRefName":"nf-add-meal-options-to-main-page","number":18,"title":"NF - Adds \"Meals Offered Today\" Column to Main Page","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/18"},{"author":{"id":"U_kgDOCeQtvw","is_bot":false,"login":"Helenlongjiao","name":"Longjiao Chen"},"headRefName":"helenlongjiao-refactor-relative-imports","number":16,"title":"REFACTOR: replace relative paths in imports with absolute paths","url":"https://github.com/ucsb-cs156-f25/proj-dining-f25-06/pull/16"}]
